export const SHIELD_PASSPORT_LOCAL_AUTH_SERVICE =
  "SHIELD_PASSPORT_LOCAL_AUTH_SERVICE";
export const SHIELD_PASSPORT_JWT_OPTIONS = "SHIELD_PASSPORT_JWT_OPTIONS";
export const SHIELD_PASSPORT_LOCAL_OPTIONS = "SHIELD_PASSPORT_LOCAL_OPTIONS";
